/**
* "Author:Rinkle Rose Renny"
* "Purpose: To store delivery agent details"
* "User story: TF-101"
* "Date: 25/10/2023"
*/

CREATE TABLE public.delivery (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	delivery_name varchar(100) NOT NULL,
	delivery_contact_details int4 NOT NULL,
	vehicle_number varchar(100) NOT NULL,
	delivery_availability varchar(100) NULL DEFAULT 'OPEN'::character varying,
	"version" int8 NULL,
	created_by varchar(255) NULL,
	created_date date NULL,
	created_date_time timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date date NULL,
	last_modified_date_time timestamp NULL,
	CONSTRAINT delivery_pkey PRIMARY KEY (id)
);

alter table delivery  add column is_active BOOLEAN default false;
