
/**
* "Author:Rinkle Rose Renny"
* "Purpose: To store order delivery details"
* "User story: TF-101"
* "Date: 2/11/2023"
*/
--create table delivery_details (
--	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
--	order_id int8 references orders(id) not null,
--	delivery_id int8 references delivery(id) not null,
--	customer_id int8 references customer(id) not null,
--	restaurant_id int8 references restaurant(id) not null,
--	total_time_taken int8 not null ,
--	total_distance int8 not null,
--	delivery_status varchar(100) DEFAULT 'OPEN'::character varying,
--	"version" int8 NULL,
--	created_by varchar(255) NULL,
--	created_date date NULL,
--	created_date_time timestamp NULL,
--	last_modified_by varchar(255) NULL,
--	last_modified_date date NULL,
--	last_modified_date_time timestamp NULL,
--	constraint delivery_update_pkey primary key(id)
--	);


	CREATE TABLE public.delivery_details (
    	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    	order_id int8 NOT NULL,
    	delivery_id int8 NOT NULL,
    	customer_id int8 NOT NULL,
    	restaurant_id int8 NOT NULL,
    	total_time_taken int8 NOT NULL,
    	total_distance int8 NOT NULL,
    	delivery_status varchar(100) NULL DEFAULT 'OPEN'::character varying,
    	"version" int8 NULL,
    	created_by varchar(255) NULL,
    	created_date date NULL,
    	created_date_time timestamp NULL,
    	last_modified_by varchar(255) NULL,
    	last_modified_date date NULL,
    	last_modified_date_time timestamp NULL,
    	CONSTRAINT delivery_update_pkey PRIMARY KEY (id)
    );


    -- public.delivery_details foreign keys

    ALTER TABLE public.delivery_details ADD CONSTRAINT delivery_details_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer(id);
    ALTER TABLE public.delivery_details ADD CONSTRAINT delivery_details_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.delivery(id);
    ALTER TABLE public.delivery_details ADD CONSTRAINT delivery_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
    ALTER TABLE public.delivery_details ADD CONSTRAINT delivery_details_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurant(id);